export default {
  FormCategory: [
    {
      default: null,
      list: false,
      name: "name",
      required: true,
      scalar: true,
      type: "String",
    },
  ],
  FormProduct: [
    {
      default: null,
      list: false,
      name: "name",
      required: true,
      scalar: true,
      type: "String",
    },
    {
      default: null,
      list: true,
      name: "categoryId",
      required: false,
      scalar: true,
      type: "ID",
    },
  ],
  FormSearch: [
    {
      default: null,
      list: false,
      name: "timestamp",
      required: true,
      scalar: true,
      type: "Time",
    },
    {
      default: null,
      list: false,
      name: "amount",
      required: false,
      scalar: true,
      type: "Decimal",
    },
    {
      default: null,
      list: false,
      name: "cash",
      required: false,
      scalar: true,
      type: "Float",
    },
    {
      default: null,
      list: false,
      name: "endDatetime",
      required: false,
      scalar: true,
      type: "DateTime",
    },
    {
      default: null,
      list: false,
      name: "name",
      required: false,
      scalar: true,
      type: "String",
    },
    {
      default: null,
      list: false,
      name: "startDate",
      required: false,
      scalar: true,
      type: "Date",
    },
  ],
  Item: [
    {
      default: null,
      list: false,
      name: "id",
      required: false,
      scalar: true,
      type: "ID",
    },
    {
      default: null,
      list: true,
      name: "ids",
      required: false,
      scalar: true,
      type: "ID",
    },
  ],
  Pagination: [
    {
      default: true,
      list: false,
      name: "all",
      required: false,
      scalar: true,
      type: "Boolean",
    },
    {
      default: 10,
      list: false,
      name: "limit",
      required: false,
      scalar: true,
      type: "Int",
    },
    {
      default: 10,
      list: false,
      name: "page",
      required: false,
      scalar: true,
      type: "Int",
    },
    {
      default: '"-id"',
      list: false,
      name: "sortBy",
      required: false,
      scalar: true,
      type: "String",
    },
  ],
};
