export default {
  Category: [
    {
      default: null,
      list: false,
      name: "Id",
      required: false,
      scalar: true,
      type: "String",
    },
    {
      default: null,
      list: false,
      name: "id",
      required: false,
      scalar: true,
      type: "ID",
    },
    {
      default: null,
      list: false,
      name: "name",
      required: false,
      scalar: true,
      type: "String",
    },
    {
      default: null,
      list: false,
      name: "group",
      required: false,
      scalar: false,
      type: "Group",
    },
  ],
  Error: [
    {
      default: null,
      list: true,
      name: "messages",
      required: true,
      scalar: false,
      type: null,
    },
    {
      default: null,
      list: false,
      name: "meta",
      required: true,
      scalar: true,
      type: "JSON",
    },
    {
      default: null,
      list: false,
      name: "error",
      required: true,
      scalar: true,
      type: "Boolean",
    },
  ],
  ErrorMessage: [
    {
      default: null,
      list: false,
      name: "field",
      required: false,
      scalar: true,
      type: "String",
    },
    {
      default: null,
      list: false,
      name: "type",
      required: false,
      scalar: true,
      type: "String",
    },
    {
      default: null,
      list: false,
      name: "text",
      required: false,
      scalar: true,
      type: "String",
    },
  ],
  Group: [
    {
      default: null,
      list: false,
      name: "Id",
      required: false,
      scalar: true,
      type: "String",
    },
    {
      default: null,
      list: false,
      name: "id",
      required: false,
      scalar: true,
      type: "ID",
    },
    {
      default: null,
      list: false,
      name: "name",
      required: false,
      scalar: true,
      type: "String",
    },
    {
      default: null,
      list: false,
      name: "category",
      required: false,
      scalar: false,
      type: "Category",
    },
  ],
  PageInfo: [
    {
      default: null,
      list: false,
      name: "length",
      required: true,
      scalar: true,
      type: "Int",
    },
    {
      default: null,
      list: false,
      name: "pages",
      required: true,
      scalar: true,
      type: "Int",
    },
    {
      default: null,
      list: false,
      name: "extra",
      required: true,
      scalar: true,
      type: "JSON",
    },
  ],
  Product: [
    {
      default: null,
      list: false,
      name: "Id",
      required: false,
      scalar: true,
      type: "String",
    },
    {
      default: null,
      list: false,
      name: "id",
      required: false,
      scalar: true,
      type: "ID",
    },
    {
      default: null,
      list: false,
      name: "category",
      required: false,
      scalar: false,
      type: "Category",
    },
    {
      default: null,
      list: false,
      name: "name",
      required: false,
      scalar: true,
      type: "String",
    },
    {
      default: null,
      list: true,
      name: "aliases",
      required: false,
      scalar: true,
      type: "String",
    },
    {
      default: null,
      list: false,
      name: "stock",
      required: false,
      scalar: true,
      type: "Int",
    },
    {
      default: null,
      list: false,
      name: "isAvailable",
      required: false,
      scalar: true,
      type: "Boolean",
    },
    {
      default: null,
      list: false,
      name: "createdOn",
      required: false,
      scalar: true,
      type: "DateTime",
    },
    {
      default: null,
      list: false,
      name: "availableFrom",
      required: false,
      scalar: true,
      type: "Date",
    },
    {
      default: null,
      list: false,
      name: "sameDayShippingBefore",
      required: false,
      scalar: true,
      type: "Time",
    },
    {
      default: null,
      list: false,
      name: "price",
      required: false,
      scalar: true,
      type: "Decimal",
    },
    {
      default: null,
      list: true,
      name: "notes",
      required: false,
      scalar: true,
      type: "String",
    },
    {
      default: null,
      list: false,
      name: "isObject",
      required: false,
      scalar: true,
      type: "JSON",
    },
    {
      default: null,
      list: false,
      name: "group",
      required: false,
      scalar: false,
      type: "Group",
    },
  ],
  ProductConnection: [
    {
      default: null,
      list: false,
      name: "pageInfo",
      required: true,
      scalar: false,
      type: "PageInfo",
    },
    {
      default: null,
      list: true,
      name: "edges",
      required: true,
      scalar: false,
      type: null,
    },
  ],
  ProductEdge: [
    {
      default: null,
      list: false,
      name: "node",
      required: true,
      scalar: false,
      type: "Product",
    },
    {
      default: null,
      list: false,
      name: "cursor",
      required: true,
      scalar: true,
      type: "String",
    },
  ],
};
